version: '3'

services:
  nestjs:
    image: node:20 # Use the official Node.js image as the base image
    working_dir: /app # Set the working directory inside the container to /app
    volumes:
      - .:/app # Mount the current directory to /app in the container
    env_file:
      - .env # Load environment variables from the .env file
    command: sh -c "npm install && npm run db:push && npm run start:dev" # Command to run after the container starts
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    ports:
      - '3001:3001' # Map port 3000 of the host to port 3000 in the container
    depends_on:
      - db # Ensure the db service is started before this service

  db:
    image: nouchka/sqlite3 # Use a lightweight SQLite3 image
    volumes:
      - ./prisma:/app/prisma # Mount the prisma directory to /data in the container
