export enum userRoles {
  OFFICIAL = 'OFFICIAL',
  ADMIN = 'ADMIN',
}

export enum CampaignPurpose {
  MEDICAL_EXPENSES = 'MEDICAL_EXPENSES',
  HUMANITARIAN_AID = 'HUMANITARIAN_AID',
  SOCIAL_JUSTICE_CAUSES = 'SOCIAL_JUSTICE_CAUSES',
  COMMUNITY_PROJECTS = 'COMMUNITY_PROJECTS',
  DISASTER_RELIEF = 'DISASTER_RELIEF',
}

export enum CampaaignStatus {
  OPEN = 'OPEN',
  COMPLETED = 'COMPLETED',
}

export enum DonationStatus {
  PENDING = 'PENDING',
  SUCCESSFUL = 'SUCCESSFUL',
  FAILED = 'FAILED',
}
